In [226]:
import pandas as pd
import numpy as np
import seaborn as sns 
import matplotlib.pyplot as plt
import plotly.express as px

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

In [227]:
encontro = pd.read_csv("base_segundo_encontro.csv", encoding="latin-1", sep=";")
print(encontro)

     tempo_conversa_min  risadas  pontos_comuns  nivel_timidez  \
0                   112       16              6              0
1                   102       13              2             10
2                    24        8              2              3
3                   116        7              4              0
4                    81        1              2              5
..                  ...      ...            ...            ...
995                 129       19              6              0
996                  68       17              5              6
997                 137        5              3              7
998                 123       10              1             10
999                 124        1              8              7

     mensagens_antes  iniciativa_conversa local_encontro momento_da_vida  \
0                 45                    8    Restaurante      Estressado
1                 41                    6            Bar         Estável
2                 16                    9           Café         Estável
3                  8                    4            Bar      Estressado
4                  5                    7         Parque         Estável
..               ...                  ...            ...             ...
995               25                    8            Bar         Estável
996               12                    3    Restaurante         Estável
997                7                    7         Parque         Cansado
998               27                    8            Bar      Estressado
999               29                    8           Café         Estável

    segundo_encontro
0                Sim
1                Sim
2                Sim
3                Sim
4                Não
..               ...
995              Sim
996              Sim
997              Sim
998              Não
999              Sim

[1000 rows x 9 columns]

In [228]:
x = encontro.iloc[:, 0:8]
y = encontro.iloc[:, 8]

x

,tempo_conversa_min,risadas,pontos_comuns,nivel_timidez,mensagens_antes,iniciativa_conversa,local_encontro,momento_da_vida
0,112,16,6,0,45,8,Restaurante,Estressado
1,102,13,2,10,41,6,Bar,Estável
2,24,8,2,3,16,9,Café,Estável
3,116,7,4,0,8,4,Bar,Estressado
4,81,1,2,5,5,7,Parque,Estável
...,...,...,...,...,...,...,...,...
995,129,19,6,0,25,8,Bar,Estável
996,68,17,5,6,12,3,Restaurante,Estável
997,137,5,3,7,7,7,Parque,Cansado
998,123,10,1,10,27,8,Bar,Estressado
999,124,1,8,7,29,8,Café,Estável

In [ ]:
labelEncoderLocalEncontro = LabelEncoder()
labelEncoderMomentoVida = LabelEncoder()

x['local_encontro'] = labelEncoderLocalEncontro.fit_transform(x.iloc[:, 6])
x['momento_da_vida'] = labelEncoderMomentoVida.fit_transform(x.iloc[:, 7])

x

,tempo_conversa_min,risadas,pontos_comuns,nivel_timidez,mensagens_antes,iniciativa_conversa,local_encontro,momento_da_vida
0,112,16,6,0,45,8,3,1
1,102,13,2,10,41,6,0,2
2,24,8,2,3,16,9,1,2
3,116,7,4,0,8,4,0,1
4,81,1,2,5,5,7,2,2
...,...,...,...,...,...,...,...,...
995,129,19,6,0,25,8,0,2
996,68,17,5,6,12,3,3,2
997,137,5,3,7,7,7,2,0
998,123,10,1,10,27,8,0,1
999,124,1,8,7,29,8,1,2

In [ ]:
x_treino, x_teste, y_treino, y_teste = train_test_split(x, y.values, test_size=0.2, random_state=42)

AttributeError: 'StandardScaler' object has no attribute 'values'